In [1]:
a=[50,45,35,40,30]
a

[50, 45, 35, 40, 30]

In [2]:
import numpy as np
mark=np.array(a)
mark

array([50, 45, 35, 40, 30])

In [3]:
d=np.mean(mark)
d

np.float64(40.0)

In [4]:
np.max(mark)

np.int64(50)

In [5]:
np.min(mark)

np.int64(30)

In [7]:
e=np.zeros([4,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
f=np.ones([5,5])
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
g=np.eye(6)
g

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
h=np.linspace(1,20,10)
h

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [16]:
group=([1,2,6,2,4,5,3,5,4,6])
i=np.unique(group)
i

array([1, 2, 3, 4, 5, 6])

In [17]:
j=np.array([9,5,7,3,1,6,2,8,4])
np.sort(j)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
k=np.array([[1,2,3],[4,5,6]])
l=np.array([[1,2],
           [3,4],
           [5,6]])
m=np.dot(k,l)
m

array([[22, 28],
       [49, 64]])

In [20]:
n=np.array([[1,2],[3,4],[5,6]])
n.T

array([[1, 3, 5],
       [2, 4, 6]])

In [23]:
o=np.array([1,2,3])
p=np.array([4,5,6])
np.concatenate((o,p))


array([1, 2, 3, 4, 5, 6])

In [24]:
q=np.array([1,2,3,4,5])
r=np.array([6,7,8,9,0])
q+r

array([ 7,  9, 11, 13,  5])

In [25]:
q-r

array([-5, -5, -5, -5,  5])

In [26]:
q*r

array([ 6, 14, 24, 36,  0])

In [30]:
s=np.random.rand(2,3)
s

array([[0.44813664, 0.92583106, 0.38006511],
       [0.67076979, 0.8669057 , 0.62875942]])

In [37]:
t=np.array([9,5,7,3,1,6,2,8,4,0])
u=np.reshape(t,(2,5))
u

array([[9, 5, 7, 3, 1],
       [6, 2, 8, 4, 0]])

In [40]:
v=np.arange(20).reshape(2,10)
v


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [42]:
w=np.array([9,5,7,3,1,6,2,8,4,0])
x=w[4:9]
x

array([1, 6, 2, 8, 4])